BIC_COMPANY_MAP = {
    # --- Küresel Ana Hat Operatörleri ---
    "MSCU": "MEDITERRANEAN SHIPPING COMPANY (MSC)",
    "MAEU": "MAERSK LINE",
    "MSKU": "MAERSK LINE",
    "HLXU": "HAPAG-LLOYD",
    "HLCU": "HAPAG-LLOYD",
    "CMAU": "CMA CGM",
    "CGMU": "CMA CGM",
    "COSU": "COSCO SHIPPING LINES",
    "CBHU": "COSCO SHIPPING LINES",
    "EMCU": "EVERGREEN LINE",
    "EISU": "EVERGREEN LINE",
    "ONEY": "ONE (OCEAN NETWORK EXPRESS)",
    "NYKU": "ONE (OCEAN NETWORK EXPRESS)",
    "OOLU": "ORIENT OVERSEAS CONTAINER LINE (OOCL)",
    "HDMU": "HMM (HYUNDAI MERCHANT MARINE)",
    "HMMU": "HMM (HYUNDAI MERCHANT MARINE)",
    "YMLU": "YANG MING MARINE TRANSPORT",
    "ZIMU": "ZIM INTEGRATED SHIPPING SERVICES",
    "PILU": "PACIFIC INTERNATIONAL LINES (PIL)",
    "ONEU": "ONE (OCEAN NETWORK EXPRESS)",

    # --- Büyük Operatörler (ek prefix'ler) ---
    "SUDU": "HAMBURG SUD",
    "MRKU": "MAERSK LINE",
    "APHU": "APL (CMA CGM GROUP)",
    "APRU": "APL (CMA CGM GROUP)",
    "SEAU": "SEALAND (MAERSK GROUP)",
    "MSDU": "MSC MEDITERRANEAN SHIPPING",
    "GCXU": "GOLD CONTAINER (CMA CGM)",

    # --- Türkiye ve Bölgesel Hatlar ---
    "TRKU": "TURKON LINE",
    "ARKU": "ARKAS LINE",
    "EMEU": "EIMSKIP",
    "SMLU": "SITC CONTAINER LINES",
    "WHLU": "WAN HAI LINES",
    "SAFU": "SAFMARINE (MAERSK GROUP)",
    "MEDU": "MEDKON LINES",

    # --- Konteyner Kiralama (ek) ---
    "TCKU": "TRITON CONTAINER INTERNATIONAL",
    "CAIU": "CAI INTERNATIONAL",
    "FSCU": "FLORENS CONTAINER SERVICES",
    "GLDU": "GOLD FIELDS CONTAINER LEASING",
    "BMOU": "BLUE OCEAN CONTAINER LEASING",
    "LYKU": "LYKES LINES",

    # --- Konteyner Kiralama Şirketleri ---
    "TGHU": "TEXTAINER",
    "TRLU": "TEXTAINER",
    "TGBU": "TEXTAINER",
    "CAXU": "CAI INTERNATIONAL",
    "SEGU": "SEACO GLOBAL",
    "FCIU": "BEACON INTERMODAL LEASING",
    "BEAU": "BEACON INTERMODAL LEASING",
    "DRYU": "DREYER HOLDINGS",
    "CLHU": "CONTAINER LEASING INTERNATIONAL (CLI)",
    "GESU": "GATX INTERMODAL",
    "TOLU": "TRITON INTERNATIONAL",
    "TTXU": "TRITON INTERNATIONAL",
    "DTXU": "SEACUBE CONTAINER LEASING",
    "SCZU": "SEACUBE CONTAINER LEASING",
    "FLXU": "FLEXI-VAN LEASING",
    "TRHU": "TRANSAMERICA LEASING",
    "PINU": "PINNACLE LEASING",
    "BSIU": "BLUE SKY INTERMODAL",
    "INBU": "INTERPOOL",
    "IPXU": "INTERPOOL",
    "CRXU": "CRONOS CONTAINERS",
    "GATU": "GATX INTERMODAL",
    "PERU": "PERMA CONTAINER",
    "PONU": "P&O NEDLLOYD",

    # --- Eksik Eklenen Popüler Prefix'ler ---
    "TDCU": "PT TRADECORP INDONESIA",
    "XINU": "X-PRESS FEEDERS",
    "HASU": "HAPAG-LLOYD",
    "UACU": "UASC (UNITED ARAB SHIPPING COMPANY)",
    "KKLU": "K LINE (KAWASAKI KISEN KAISHA)",
    "TALU": "TRITON INTERNATIONAL (TAL INTERNATIONAL)",

    # --- Triton Ek Prefix'leri ---
    "TCTU": "TCT TRANS CONTINENTAL TANK LTD",
    "TCNU": "TRITON CONTAINER INTERNATIONAL",
    "TTNU": "TRITON CONTAINER INTERNATIONAL",
    "TRIU": "TRITON CONTAINER INTERNATIONAL",

    # --- COSCO / China Shipping ---
    "CCLU": "CHINA SHIPPING CONTAINER LINES (COSCO)",
    "CSLU": "CHINA SHIPPING CONTAINER LINES (COSCO)",
    "CSNU": "COSCO SHIPPING LINES",

    # --- Ek Maersk / Hapag Prefix'leri ---
    "MNBU": "MAERSK LINE",
    "HLBU": "HAPAG-LLOYD",

    # --- Diğer Hat Operatörleri ---
    "YMMU": "YANG MING MARINE TRANSPORT",
    "ACLU": "ATLANTIC CONTAINER LINE",
    "MOFU": "MITSUI O.S.K. LINES (MOL)",
    "AMKU": "AUSTRAL ASIA LINE",
    "EOLU": "EVERGREEN LINE",
}
