BIC_COMPANY_MAP = {
    # --- Küresel Ana Hat Operatörleri ---
    "MSCU": "MEDITERRANEAN SHIPPING COMPANY (MSC)",
    "MAEU": "MAERSK LINE",
    "MSKU": "MAERSK LINE",
    "HLXU": "HAPAG-LLOYD",
    "HLCU": "HAPAG-LLOYD",
    "CMAU": "CMA CGM",
    "CGMU": "CMA CGM",
    "COSU": "COSCO SHIPPING LINES",
    "CBHU": "COSCO SHIPPING LINES",
    "EMCU": "EVERGREEN LINE",
    "EISU": "EVERGREEN LINE",
    "ONEY": "ONE (OCEAN NETWORK EXPRESS)",
    "NYKU": "ONE (OCEAN NETWORK EXPRESS)",
    "OOLU": "ORIENT OVERSEAS CONTAINER LINE (OOCL)",
    "HDMU": "HMM (HYUNDAI MERCHANT MARINE)",
    "HMMU": "HMM (HYUNDAI MERCHANT MARINE)",
    "YMLU": "YANG MING MARINE TRANSPORT",
    "ZIMU": "ZIM INTEGRATED SHIPPING SERVICES",
    "PILU": "PACIFIC INTERNATIONAL LINES (PIL)",
    "ONEU": "ONE (OCEAN NETWORK EXPRESS)",

    # --- Büyük Operatörler (ek prefix'ler) ---
    "SUDU": "HAMBURG SUD",
    "MRKU": "MAERSK LINE",
    "APHU": "APL (CMA CGM GROUP)",
    "APRU": "APL (CMA CGM GROUP)",
    "SEAU": "SEALAND (MAERSK GROUP)",
    "MSDU": "MSC MEDITERRANEAN SHIPPING",
    "GCXU": "GOLD CONTAINER (CMA CGM)",

    # --- Türkiye ve Bölgesel Hatlar ---
    "TRKU": "TURKON LINE",
    "ARKU": "ARKAS LINE",
    "EMEU": "EIMSKIP",
    "SMLU": "SITC CONTAINER LINES",
    "WHLU": "WAN HAI LINES",
    "SAFU": "SAFMARINE (MAERSK GROUP)",
    "MEDU": "MEDKON LINES",

    # --- Konteyner Kiralama (ek) ---
    "TCKU": "TRITON CONTAINER INTERNATIONAL",
    "CAIU": "CAI INTERNATIONAL",
    "FSCU": "FLORENS CONTAINER SERVICES",
    "GLDU": "GOLD FIELDS CONTAINER LEASING",
    "BMOU": "BLUE OCEAN CONTAINER LEASING",
    "LYKU": "LYKES LINES",

    # --- Konteyner Kiralama Şirketleri ---
    "TGHU": "TEXTAINER",
    "TRLU": "TEXTAINER",
    "TGBU": "TEXTAINER",
    "CAXU": "CAI INTERNATIONAL",
    "SEGU": "SEACO GLOBAL",
    "FCIU": "BEACON INTERMODAL LEASING",
    "BEAU": "BEACON INTERMODAL LEASING",
    "DRYU": "DREYER HOLDINGS",
    "CLHU": "CONTAINER LEASING INTERNATIONAL (CLI)",
    "GESU": "GATX INTERMODAL",
    "TOLU": "TRITON INTERNATIONAL",
    "TTXU": "TRITON INTERNATIONAL",
    "DTXU": "SEACUBE CONTAINER LEASING",
    "SCZU": "SEACUBE CONTAINER LEASING",
    "FLXU": "FLEXI-VAN LEASING",
    "TRHU": "TRANSAMERICA LEASING",
    "PINU": "PINNACLE LEASING",
    "BSIU": "BLUE SKY INTERMODAL",
    "INBU": "INTERPOOL",
    "IPXU": "INTERPOOL",
    "CRXU": "CRONOS CONTAINERS",
    "GATU": "GATX INTERMODAL",
    "PERU": "PERMA CONTAINER",
    "PONU": "P&O NEDLLOYD",

    # --- Eksik Eklenen Popüler Prefix'ler ---
    "TDCU": "PT TRADECORP INDONESIA",
    "XINU": "X-PRESS FEEDERS",
    "HASU": "HAPAG-LLOYD",
    "UACU": "UASC (UNITED ARAB SHIPPING COMPANY)",
    "KKLU": "K LINE (KAWASAKI KISEN KAISHA)",
    "TALU": "TRITON INTERNATIONAL (TAL INTERNATIONAL)",

    # --- Triton Ek Prefix'leri ---
    "TCTU": "TCT TRANS CONTINENTAL TANK LTD",
    "TCNU": "TRITON CONTAINER INTERNATIONAL",
    "TTNU": "TRITON CONTAINER INTERNATIONAL",
    "TRIU": "TRITON CONTAINER INTERNATIONAL",

    # --- COSCO / China Shipping ---
    "CCLU": "CHINA SHIPPING CONTAINER LINES (COSCO)",
    "CSLU": "CHINA SHIPPING CONTAINER LINES (COSCO)",
    "CSNU": "COSCO SHIPPING LINES",

    # --- Ek Maersk / Hapag Prefix'leri ---
    "MNBU": "MAERSK LINE",
    "HLBU": "HAPAG-LLOYD",

    # --- Diğer Hat Operatörleri ---
    "YMMU": "YANG MING MARINE TRANSPORT",
    "ACLU": "ATLANTIC CONTAINER LINE",
    "MOFU": "MITSUI O.S.K. LINES (MOL)",
    "AMKU": "AUSTRAL ASIA LINE",
    "EOLU": "EVERGREEN LINE",

    # --- Evergreen Ek Prefix'leri ---
    "TCKU": "TRITON CONTAINER INTERNATIONAL",
    "EGHU": "EVERGREEN LINE",
    "EGSU": "EVERGREEN LINE",
    "EVRU": "EVERGREEN LINE",

    # --- Hapag-Lloyd Ek ---
    "HPLU": "HAPAG-LLOYD",
    "HLDU": "HAPAG-LLOYD",

    # --- MSC Ek ---
    "MEDU": "MEDITERRANEAN SHIPPING COMPANY (MSC)",
    "MSMU": "MEDITERRANEAN SHIPPING COMPANY (MSC)",

    # --- CMA CGM Ek ---
    "CMDU": "CMA CGM",
    "CNIU": "CMA CGM",
    "ANLU": "CMA CGM / ANL",
    "ANNU": "CMA CGM / ANL",

    # --- NYK / ONE ---
    "KNLU": "K LINE (KAWASAKI KISEN KAISHA)",
    "KNTU": "K LINE (KAWASAKI KISEN KAISHA)",
    "MOLU": "MITSUI O.S.K. LINES (MOL)",
    "MONU": "MITSUI O.S.K. LINES (MOL)",

    # --- PIL / SITC / Wan Hai ---
    "SITC": "SITC CONTAINER LINES",
    "WHLC": "WAN HAI LINES",
    "WHSU": "WAN HAI LINES",

    # --- Seacastle / Sky ---
    "SKYU": "SEACASTLE CONTAINER LEASING",
    "SCMU": "SEACASTLE CONTAINER LEASING",

    # --- Küçük / Bölgesel Operatörler ---
    "ZCSU": "ZIM INTEGRATED SHIPPING",
    "SEAL": "SEALAND (MAERSK GROUP)",
    "SINU": "SINOKOR MERCHANT MARINE",
    "MCPU": "MACFARLANE CONTAINERS",
    "MFSU": "MITSUBISHI FUSO CONTAINER",
    "AMFU": "ANTONG HOLDINGS",
    "ATHU": "ANTONG HOLDINGS",
    "FBIU": "FBL LOGISTIC",
    "PCIU": "PACIFIC CONTAINER LEASING",
    "FUJU": "FUJI TRADING",
    "NARU": "NIKAR MARITIME",
    "SKHU": "SEACO GLOBAL",
    "TEMU": "TEMU (PDD HOLDINGS)",
    "RFCU": "RAINBOW CONTAINER LEASING",
    "CNFU": "CHONGQING NEW FORCE",
    "SZLU": "SHENZHEN LOVOL",
    "CXDU": "CX CONTAINERS",
    "PDLU": "PDL (PACIFIC DIRECT LINE)",
    "SFCU": "STAR FACILITIES",
    "SPHU": "SPIL (SALAM PACIFIC INDONESIA)",
    "PTCU": "PACIFIC TYCOON CONTAINERS",
    "UESU": "UNITED EUROPEAN CAR CARRIERS",
    "UGKU": "UGLAND CONTAINER LINE",
    "MEAU": "MEDITERRANEAN AFRICA LINE",
    "GEBU": "GEOMETRIC CONTAINER LEASING",
    "ECMU": "EURO CONTAINER MARINE",
    "DULU": "DUBAI PORT WORLD CONTAINERS",
    "IKCU": "IKC CONTAINER LEASING",
    "LSCU": "LS CONTAINER LINE",
    "LHBU": "LIANHE CONTAINER LEASING",
    "JXLU": "JINXIN SHIPPING",
    "SNBU": "SINO CONTAINER",
    "YMAU": "YANG MING MARINE TRANSPORT",
    "YCLU": "YANG CHENG CONTAINER LEASING",
    "ZCLU": "ZHEJIANG CONTAINER LINE",
}
