BIC_COMPANY_MAP = {
    # --- Küresel Ana Hat Operatörleri ---
    "MSCU": "Mediterranean Shipping Company (MSC)",
    "MAEU": "Maersk Line",
    "MSKU": "Maersk Line",
    "HLXU": "Hapag-Lloyd",
    "HLCU": "Hapag-Lloyd",
    "CMAU": "CMA CGM",
    "CGMU": "CMA CGM",
    "COSU": "COSCO Shipping Lines",
    "CBHU": "COSCO Shipping Lines",
    "EMCU": "Evergreen Line",
    "EISU": "Evergreen Line",
    "ONEY": "ONE (Ocean Network Express)",
    "NYKU": "ONE (Ocean Network Express)",
    "OOLU": "Orient Overseas Container Line (OOCL)",
    "HMMU": "HMM (Hyundai Merchant Marine)",
    "YMLU": "Yang Ming Marine Transport",
    "ZIMU": "ZIM Integrated Shipping Services",
    "PILU": "Pacific International Lines (PIL)",
    "ONEU": "ONE (Ocean Network Express)",

    # --- Büyük Operatörler (ek prefix'ler) ---
    "SUDU": "Hamburg Süd",
    "MRKU": "Maersk Line",
    "APHU": "APL (CMA CGM Group)",
    "APRU": "APL (CMA CGM Group)",
    "SEAU": "Sealand (Maersk Group)",
    "MSDU": "MSC Mediterranean Shipping",
    "GCXU": "Gold Container (CMA CGM)",

    # --- Türkiye ve Bölgesel Hatlar ---
    "TRKU": "Turkon Line",
    "ARKU": "Arkas Line",
    "EMEU": "Eimskip",
    "SMLU": "SITC Container Lines",
    "WHLU": "Wan Hai Lines",
    "SAFU": "Safmarine (Maersk Group)",
    "MEDU": "Medkon Lines",

    # --- Konteyner Kiralama (ek) ---
    "TCKU": "Triton Container International",
    "CAIU": "CAI International",
    "FSCU": "Florens Container Services",
    "GLDU": "Gold Fields Container Leasing",
    "BMOU": "Blue Ocean Container Leasing",
    "LYKU": "Lykes Lines",

    # --- Konteyner Kiralama Şirketleri ---
    "TGHU": "Textainer",
    "TRLU": "Textainer",
    "TGBU": "Textainer",
    "CAXU": "CAI International",
    "SEGU": "Seaco Global",
    "FCIU": "Beacon Intermodal Leasing",
    "BEAU": "Beacon Intermodal Leasing",
    "DRYU": "Dreyer Holdings",
    "CLHU": "Container Leasing International (CLI)",
    "GESU": "GATX Intermodal",
    "TOLU": "Triton International",
    "TTXU": "Triton International",
    "DTXU": "SeaCube Container Leasing",
    "SCZU": "SeaCube Container Leasing",
    "FLXU": "Flexi-Van Leasing",
    "TRHU": "Transamerica Leasing",
    "PINU": "Pinnacle Leasing",
    "BSIU": "Blue Sky Intermodal",
    "INBU": "Interpool",
    "IPXU": "Interpool",
    "CRXU": "Cronos Containers",
    "GATU": "GATX Intermodal",
    "PERU": "Perma Container",
    "PONU": "P&O Nedlloyd",

    # --- Eksik Eklenen Popüler Prefix'ler ---
    "TDCU": "PT Tradecorp Indonesia",
    "OOLU": "Orient Overseas Container Line (OOCL)", # Çift tanımları önlemek için güncellendi
    "BMOU": "Blue Ocean Container Leasing",
    "XINU": "X-Press Feeders",
    "HASU": "Hapag-Lloyd",
    "UACU": "UASC (United Arab Shipping Company)",
    "KKLU": "K Line (Kawasaki Kisen Kaisha)",
    "NYKU": "Nippon Yusen Kaisha (NYK Line)",
    "PONU": "P&O Nedlloyd",
    "MSCU": "Mediterranean Shipping Company",
    "TALU": "Triton International (TAL International)",
    "MEDU": "Medkon Lines",
}